name: quick_usb
publish_to: none
description: A cross-platform (Android/Windows/macOS/Linux) USB plugin for Flutter
version: 0.5.0

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6
  libusb: 
    git: 
      url: https://github.com/ziakhan110/libusb.dart
      ref: a770d1a3d16069fe7a84480e790a91f2e4ed6ae5
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.quick_usb
        pluginClass: QuickUsbPlugin
        dartPluginClass: QuickUsbAndroid
      windows:
        hasRegistration: false
        dartPluginClass: QuickUsbDesktop
      macos:
        hasRegistration: true
        dartPluginClass: QuickUsbDesktop
      linux:
        hasRegistration: true
        dartPluginClass: QuickUsbDesktop
 